# Generated by Django 6.0.7 on 2026-07-18 19:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('type_transaction', models.CharField(choices=[('recette', 'Recette'), ('depense', 'Depense')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('libelle', models.CharField(max_length=200)),
                ('date_transaction', models.DateField(default=django.utils.timezone.now)),
                ('mode_reglement', models.CharField(choices=[('especes', 'Especes'), ('virement', 'Virement'), ('cheque', 'Cheque')], default='especes', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('valide', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.categoriedepense')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'ordering': ['-date_transaction', '-cree_le'],
            },
        ),
    ]
