# Generated by Django 6.0.7 on 2026-07-18 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, default='bi-tag', max_length=50)),
                ('couleur', models.CharField(blank=True, default='#3b82f6', max_length=7)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('supprime', models.BooleanField(default=False)),
                ('supprime_le', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('code_barre', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prix_vente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prix_location', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('unite', models.CharField(choices=[('pce', 'Piece'), ('kg', 'Kilogramme'), ('l', 'Litre'), ('m', 'Metre'), ('boite', 'Boite'), ('carton', 'Carton'), ('forfait', 'Forfait')], default='pce', max_length=10)),
                ('quantite_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=5, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('peut_vendre', models.BooleanField(default=True)),
                ('peut_louer', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='produits.categorie')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='fournisseurs.fournisseur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entree'), ('sortie_vente', 'Sortie vente'), ('sortie_service', 'Sortie service'), ('sortie_location', 'Sortie location'), ('retour_location', 'Retour location'), ('ajustement', 'Ajustement'), ('perte', 'Perte/Casse')], max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_avant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_apres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raison', models.CharField(blank=True, max_length=200)),
                ('reference_doc', models.CharField(blank=True, max_length=50)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_prix_achat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nouveau_prix_achat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ancien_prix_vente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nouveau_prix_vente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_prix', to='produits.produit')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
