# Generated by Django 6.0.7 on 2026-07-18 19:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('produits', '0001_initial'),
        ('ventes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreDeTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('suspendu', 'Suspendu'), ('termine', 'Termine'), ('livre', 'Livre'), ('annule', 'Annule')], default='en_attente', max_length=20)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('objet_service', models.CharField(max_length=200)),
                ('description_probleme', models.TextField(blank=True)),
                ('diagnostic', models.TextField(blank=True)),
                ('travaux_effectues', models.TextField(blank=True)),
                ('note_client', models.TextField(blank=True)),
                ('date_entree', models.DateField(default=django.utils.timezone.now)),
                ('date_debut_travaux', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('cout_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cout_pieces', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='clients.client')),
                ('facture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='ventes.facture')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_assignes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordre de travail',
                'ordering': ['-date_entree', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='FichierService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('fichier', models.FileField(upload_to='services/')),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='services.ordredetravail')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='OutilService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unite', models.CharField(default='unite', max_length=30)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('inclure_dans_facture', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outils_utilises', to='services.ordredetravail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PieceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_utilisees', to='services.ordredetravail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
