# Generated by Django 6.0.7 on 2026-07-18 19:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('produits', '0001_initial'),
        ('ventes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_devis', models.DateField(default=django.utils.timezone.now)),
                ('date_validite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoye'), ('accepte', 'Accepte'), ('refuse', 'Refuse'), ('expire', 'Expire'), ('converti', 'Converti')], default='brouillon', max_length=20)),
                ('remise_globale', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='clients.client')),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_origine', to='ventes.facture')),
            ],
            options={
                'verbose_name': 'Devis',
                'ordering': ['-date_devis', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis.devis')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.produit')),
            ],
            options={
                'ordering': ['ordre', 'cree_le'],
            },
        ),
    ]
