# Generated by Django 6.0.7 on 2026-07-18 19:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('produits', '0001_initial'),
        ('ventes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin_prevue', models.DateTimeField()),
                ('date_fin_reelle', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminee'), ('en_retard', 'En retard'), ('annulee', 'Annulee')], default='en_cours', max_length=20)),
                ('depot_garantie', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalite_retard', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='clients.client')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='ventes.facture')),
            ],
            options={
                'verbose_name': 'Location',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ArticleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('prix_location_jour', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nombre_jours', models.PositiveIntegerField(default=1)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='locations.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
