# Generated by Django 6.0.7 on 2026-07-18 19:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_facture', models.DateField(default=django.utils.timezone.now)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('partielle', 'Partiellement payee'), ('payee', 'Payee'), ('annulee', 'Annulee'), ('avoir', 'Avoir')], default='brouillon', max_length=20)),
                ('remise_globale', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sous_total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_remise', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='clients.client')),
                ('vendeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_vendues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'ordering': ['-date_facture', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.facture')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.produit')),
            ],
            options={
                'ordering': ['ordre', 'cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('mode', models.CharField(choices=[('especes', 'Especes'), ('virement', 'Virement'), ('cheque', 'Cheque'), ('cb', 'Carte bancaire'), ('credit', 'Credit')], default='especes', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ventes.facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
