# Generated by Django 6.0.7 on 2026-07-18 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchatFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_achat', models.DateField(default=django.utils.timezone.now)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('receptionne', 'Receptionne'), ('paye', 'Paye'), ('annule', 'Annule')], default='en_attente', max_length=20)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Achat fournisseur',
                'ordering': ['-date_achat', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(blank=True, max_length=300)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
