# Generated by Django 6.0.7 on 2026-07-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('supprime', models.BooleanField(default=False)),
                ('supprime_le', models.DateTimeField(blank=True, null=True)),
                ('adresse_ligne1', models.CharField(blank=True, max_length=200)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('wilaya', models.CharField(blank=True, max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('administration', 'Administration')], default='particulier', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('telephone2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('registre_commerce', models.CharField(blank=True, max_length=50)),
                ('nif', models.CharField(blank=True, max_length=20)),
                ('nis', models.CharField(blank=True, max_length=20)),
                ('limite_credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remise_defaut', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
    ]
